Test for reference UTxO with SimpleScripts
input-output-hk/cardano-node-tests pull request #1302
Opened 2022-08-03 01:50 UTC by mkoura

2022-08-03 07:45 UTC, saratomaz commented on cardano_node_tests/tests/test_scripts.py
> +    """Fund a Plutus script and create the locked UTxO, collateral UTxO and reference script."""
update description

2022-08-03 07:46 UTC, saratomaz commented on cardano_node_tests/tests/test_scripts.py
> +    """Fund a Plutus script and create the locked UTxO, collateral UTxO and reference script."""
update description

2022-08-03 07:46 UTC, saratomaz requested changes
update description

2022-08-04 16:40 UTC, mkoura commented on cardano_node_tests/tests/test_scripts.py
> +    """Fund a Plutus script and create the locked UTxO, collateral UTxO and reference script."""
What's wrong with the description?

2022-08-06 21:56 UTC, mkoura commented on cardano_node_tests/tests/test_scripts.py
> +    """Fund a Plutus script and create the locked UTxO, collateral UTxO and reference script."""
I get it, it's not plutus :-)

2022-08-06 22:14 UTC, merged