test delegation and withdraw using plutus v2 reference script
input-output-hk/cardano-node-tests pull request #1353
Opened 2022-09-01 09:35 UTC by saratomaz

2022-09-01 09:39 UTC, saratomaz commented on cardano_node_tests/tests/test_plutus_v2_delegation.py
> +        dbsync_utils.check_plutus_cost(
I am getting different values on plutus cost:
```
raise AssertionError("\n".join(errors))
E           AssertionError: time: 218855869 vs 213184888
E           space: 686154 vs 670528
E           fixed cost: 55371 vs 54061
```

But don't understand why, already compare the transactions and doesn't look anything wrong:

tx_raw_output tx checked on dbsync:
```
['transaction', 'build', 
'--tx-in-collateral', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#3', 
'--certificate-file', 'test_delegate_deregister_ci0_mku_addr0_stake_dereg.cert', 
'--certificate-tx-in-reference', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#6', 
'--certificate-plutus-script-v2', 
'--certificate-reference-tx-in-redeemer-file', 'plutus/42.redeemer', 
'--tx-in-collateral', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#2', 
'--withdrawal', 'stake_test17zwga8d8lq0re2gysheja0hunqfhezkzvzs89gqvf2h3gtgtc7vzc+11375945', 
'--withdrawal-tx-in-reference', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#6', 
'--withdrawal-plutus-script-v2', 
'--withdrawal-reference-tx-in-redeemer-file', 'plutus/42.redeemer', 
'--protocol-params-file', 'pparams-qsgt.json', 
'--tx-in', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#5', 
'--change-address', 'addr_test1yq89239mp3yt9ese9mkchvck66lvqersgfafxxdh80nhk95u36w607q78j5sfp0n96l0exqn0j9vyc9qw2sqcj40zsksdhp0g9', 
'--out-file', 'test_delegate_deregister_ci0_mku_dereg_withdraw_tx.body', 
'--babbage-era', '--testnet-magic', '42']
```

tx that calculates plutus cost:
```
['transaction', 'build', 
'--tx-in-collateral', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#3', 
'--certificate-file', 'test_delegate_deregister_ci0_mku_addr0_stake_dereg.cert', 
'--certificate-tx-in-reference', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#6', 
'--certificate-plutus-script-v2', 
'--certificate-reference-tx-in-redeemer-file', '/plutus/42.redeemer', 
'--tx-in-collateral', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#2', 
'--withdrawal', 'stake_test17zwga8d8lq0re2gysheja0hunqfhezkzvzs89gqvf2h3gtgtc7vzc+11375945', 
'--withdrawal-tx-in-reference', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#6', 
'--withdrawal-plutus-script-v2', 
'--withdrawal-reference-tx-in-redeemer-file', 'plutus/42.redeemer', 
'--protocol-params-file', 'pparams-qsgt.json', 
'--tx-in', '926cdbc4bb5f241723ed2ffd086b91671e8bc54343c72e20e97fb1f90ddde3fe#5', 
'--change-address', 'addr_test1yq89239mp3yt9ese9mkchvck66lvqersgfafxxdh80nhk95u36w607q78j5sfp0n96l0exqn0j9vyc9qw2sqcj40zsksdhp0g9', 
'--calculate-plutus-script-cost', 'test_delegate_deregister_ci0_mku_dereg_withdraw_plutus.cost', 
'--babbage-era', '--testnet-magic', '42']
```

2022-09-05 11:31 UTC, mkoura requested changes
There's very little difference between `test_plutus_delegation.py` and `test_plutus_v2_delegation.py`. Therefore I suggest to parametrize the test `test_delegate_deregister` in `test_plutus_delegation.py`.

2022-09-08 15:54 UTC, mkoura requested changes

2022-09-09 23:39 UTC, mkoura approved these changes

2022-09-13 08:33 UTC, merged