test 'query utxo' with invalid data
input-output-hk/cardano-node-tests pull request #1686
Opened 2023-02-28 12:14 UTC by saratomaz

2023-03-01 11:43 UTC, saratomaz commented
Later I will move the tests related to `query utxo` to a new class `TestQueryUTxO`, I didn't do it on this PR because the changes would be very messy.

2023-03-06 14:42 UTC, mkoura requested changes

2023-03-06 14:42 UTC, mkoura commented on cardano_node_tests/tests/test_cli.py
> +    @common.hypothesis_settings()
You can likely use `@common.hypothesis_settings(max_examples=200)` or even "300". We want test runtime under one minute. Default value is 100 and I assume this test is very fast.
Same for test bellow.

2023-03-07 11:20 UTC, mkoura approved these changes

2023-03-07 11:20 UTC, merged