test 'query tip'
input-output-hk/cardano-node-tests pull request #1690
Opened 2023-03-03 16:09 UTC by saratomaz

2023-03-03 16:28 UTC, saratomaz commented
https://github.com/input-output-hk/cardano-node/issues/3878

2023-03-06 14:52 UTC, mkoura requested changes

2023-03-06 14:52 UTC, mkoura commented on cardano_node_tests/tests/test_cli.py
> +            "slotInEpoch",
This will not work in latest released node version.

2023-03-06 14:52 UTC, mkoura commented on cardano_node_tests/tests/test_cli.py
> +        ), "The output fields of 'query tip' are not the expected"
I don't think that "are not the expected" is grammatically correct.
Could be "... not the expected ones", or even better "Unexpected fields in `query tip` output"

2023-03-06 14:52 UTC, mkoura commented on cardano_node_tests/tests/test_cli.py
> +        ), "'slotsToEpochEnd' is not the expected"
Maybe "'slotsToEpochEnd' doesn't have the expected value"?

2023-03-06 14:52 UTC, mkoura commented on cardano_node_tests/tests/test_cli.py
> +        ), f"The 'era' reported is not the expected: {tip_out['era']} != {expected_era}"
Maybe "'era' doesn't have the expected value: ..."?

2023-03-07 11:15 UTC, mkoura approved these changes

2023-03-07 11:15 UTC, merged