Remove old xfails from kes tests
input-output-hk/cardano-node-tests pull request #1793
Opened 2023-05-10 15:06 UTC by saratomaz

2023-05-17 21:49 UTC, mkoura requested changes
We still want the `check_kes_period_info_result` to collect errors, not to abort tests. That would happen when calling `.finish_test()`.

I think we could leave the code as it was, and just add "blocking" checks into `get_xfails` for each potential xfail error, like

```python
if "issue_4114" in error and blockers.GH(issue=4114).is_blocked():
    ...
```

2023-05-18 10:55 UTC, saratomaz commented
I renamed the function to avoid confusion with pytest xfail, since the known not blocked issues will fail.

2023-05-18 15:26 UTC, mkoura requested changes

2023-05-18 15:26 UTC, mkoura commented on cardano_node_tests/tests/kes.py
> +def get_known_fails(errors: List[str]) -> Set[str]:
What you are getting here are really XFAILs :-) So there's no need to rename this.

2023-05-18 15:43 UTC, mkoura commented on cardano_node_tests/tests/test_kes.py
> +                pytest.fail(" ".join(known_fails))
This should be `pytest.xfail`

2023-05-18 15:43 UTC, mkoura commented on cardano_node_tests/tests/test_staking_no_rewards.py
> +                pytest.fail(" ".join(known_fails))
This should be `pytest.xfail`

2023-05-19 10:11 UTC, mkoura approved these changes

2023-05-19 10:11 UTC, merged